language: php
sudo: false
notifications:
  email:
    on_success: never
    on_failure: change
php:
- 5.3
- 5.6
- 7
- hhvm
matrix:
  include:
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
  allow_failures:
  - php: hhvm
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit
after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh
  | bash
env:
  matrix:
  - WP_VERSION=4.3.1 WP_MULTISITE=0
  - WP_VERSION=4.3.1 WP_MULTISITE=1
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=1
  - WP_VERSION=trunk WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=1
  global:
  - SVN_REPO: https://plugins.svn.wordpress.org/pppp/
  - secure: e+UzGpMylOcnoclPz5NkJm0yynmP/PFYsVOTh9GiU2VaWJKJECRsbNhpIMaQBoRqwft8ylZ12E7kos/LNLtMdd6L/Se8u+zO+xE6wbX562Bh41xqXHw5mK6juAMzVs9U/Qo6ijIsxAMpf1dOGQMDEeKG53B4X7JpI9t1cuT21cE=
